name: test for tectonic

on: 
  pull_request:
    paths:
      - '**.tex'

env:
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Fetch'
      run: git fetch --depth 1 origin ${TARGET_BRANCH}
    - name: 'Set up tectonic'
      uses: wtfjoke/setup-tectonic@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Compilation'
      run: |
        for file in $(git diff origin/${TARGET_BRANCH} HEAD --diff-filter=AM --name-only -- "*.tex") ; do
          tectonic  ${file}
        done
    - name: update file and push to remote
      run: |
        git config --global user.name "sample-push"
        git config --global user.email "sample@sample.com"
        git add -A
        git commit -m "Update PDF"
        git push origin/${TARGET_BRANCH}

